parser: babel-eslint
extends:
  - airbnb-base
  - plugin:flowtype/recommended
plugins:
  - flowtype
  - eslint-plugin-import-order-alphabetical
env:
  node: true
  mocha: true
rules:
  no-param-reassign: "off"
  no-console: "off"
  import/order: [error, newlines-between: always]
  import-order-alphabetical/order: [error]
  import/no-unresolved:
    - error
    - commonjs: true
      ignore: [ ^aws-sdk$, ^oracledb$, ^request-promise-native$, contrib/ ]
overrides:
  files:
    - src/api/v1/db/oracledb/pets-dao-example.js
  rules:
    import/order: "off"
    import-order-alphabetical/order: "off"
settings:
  import/resolver:
    babel-module: {}
