server:
  protocol: https
  hostname: ${API_HOSTNAME}
  port: ${API_PORT}
  adminPort: ${API_ADMIN_PORT}
  keyPath: /path/to/key.pem
  certPath: /path/to/server.crt
  secureProtocol: TLSv1_2_method

authentication:
  username: ${API_USER}
  password: ${API_PASSWD}

pagination:
  isPaginated: true
  maxPageSize: 500
  defaultPageSize: 25

logger:
  size: 10m
  path: logs
  pattern: YYYY-MM-DD
  archive: true

database:
  connectString: ${DB_URL}
  user: ${DB_USER}
  password: ${DB_PASSWD}
  poolMin: 30
  poolMax: 30
  poolIncrement: 0
